### ISSUE TITLE
PyDAS build version for py3+ in anaconda

### ISSUE THREAD

**Issue by hfsf** [ReactionMechanismGenerator/PyDAS#12]
Greetings.

My problem is that anaconda only provides a version of PyDAS compatible with python27, however, I would liek to use python3+. Do you guys have any plans on releasing pydas for newer python versions? I guess it would take a few development hours (if so). I've tried to port to python3 myself changing the makefile and stuff but the package does not seem to appear in my conda env. Perhaps, you could provide an official release for python3+.

**Comment by marciobez** [comment]
Hello there, I am using pyDAS too. It baffles me that one has to maintain multiple environments in python. Guess I will just have to get used to that.

Anyways... I saw you are also testing DASSLc (linux only but at least the call is the same as the original DASSL). Did you ever get it to work as desired?

**Comment by hfsf** [comment]
Hello marciobez,

Yes. I've tried this another package, however I had some issues building
from source. The author replied me a few days ago explaining how to solve
the issue. However, I would recomend you another package, named 'assimulo'.
It wraps many ODE and DAE solvers (including DASSL) and works pretty well.

Em qua, 16 de jan de 2019 08:30, marciobez <notifications@github.com
escreveu:

**Comment by marciobez** [comment]
Hello again.
What python version were you able to install assimulo in? I am struggling (badly) to get it to work on my laptop where I have multiple python installations. Miniconda 2 and 3 can't resolve the dependencies.
Any help is much appreciated.
Marcio

**Comment by hfsf** [comment]
Hello there.
Install the conda-forge repository, it pretry much solve all the
dependencies. You could google it for the steps, I'm pretty much a novice
and could not explain you how to do it. With conda-forge I've managed to
install assimulo (2.9, 3.0) in python 3.6 and 3.7. I personaly recommend
python 3.x (especially 3.6 and above) over 2.x. In case of any further
problems, or if you believe that I could help you in any way, you can email
me directly through my email hanniel88@gmail.com, to not polute this issue
thread with our future discussions. Best wishes!


Em 19 de jan de 2019 20:29, "marciobez" <notifications@github.com> escreveu:

Hello again.
What python version were you able to install assimulo in? I am struggling
(badly) to get it to work on my laptop where I have multiple python
installations. Miniconda 2 and 3 can't resolve the dependencies.
Any help is much appreciated.
Marcio

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ReactionMechanismGenerator/PyDAS/issues/12#issuecomment-455823877>,
or mute the thread

**Comment by marciobez** [comment]
Hello again my dear Hanniel,

Installing assimulo from the conda-forge repository worked like a charm. Everything fell into place! Thank you very much.

**Comment by hfsf** [comment]
Hey,
Glad to hear it! Best wishes!

Em dom, 20 de jan de 2019 23:32, marciobez <notifications@github.com
escreveu:

**Comment by JacksonBurns** [comment]
See closing comment on #14
