### ISSUE TITLE
alternative for http://www.cs.ucsb.edu/~cse/Software/daspk31.tgz? 

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/PyDAS#5]
Currently, http://www.cs.ucsb.edu/~cse/Software/daspk31.tgz, used in https://github.com/ReactionMechanismGenerator/PyDAS/blob/master/build.sh#L4, seems to be offline. 

Would it make sense to replace that URL by a location that we control?

**Comment by rwest** [comment]
Yes.
It seems to now be at 
http://www.engineering.ucsb.edu/%7Ecse/Software/daspk31.tgz
as linked from http://www.engineering.ucsb.edu/%7Ecse/software.html

Or maybe
https://cse.cs.ucsb.edu/sites/cse.cs.ucsb.edu/files/assets/daspk31.tar
as linked from 
https://cse.cs.ucsb.edu/software
