### ISSUE TITLE
Build problems with Anaconda on Mac OSX

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/PyDAS#8]
Out of the box compiling using the native RMG-Py environment.yml settings results in the following error when running `make test`

```
Traceback (most recent call last):
  File "dasslTest.py", line 10, in <module>
    from pydas.dassl import DASSL
ImportError: dlopen(/Users/connie/code/PyDAS/pydas/dassl.so, 2): Library not loaded: @rpath/./libgfortran.3.dylib
  Referenced from: /Users/connie/code/PyDAS/pydas/dassl.so
  Reason: image not found
make: *** [test] Error 1
```

Looks like it is related to a known issue in anaconda: https://github.com/ContinuumIO/anaconda-issues/issues/498

However, because I have Mac OSX El Capitan, I run into errors when trying to compile the anaconda-recipe for python2..  So far no fix for building PyDAS with gfortran natively.  However, our binary seems to work.

**Comment by JacksonBurns** [comment]
This has at some point been resolved - closing this primarily because it is stale.
